### ISSUE TITLE
cleanup your code

### ISSUE THREAD

**Issue by Waxo** [patoninho1/Serveur-flotte-de-vehicules-autonomes#4]
it's nor readable nor maintainable

**Comment by Waxo** [comment]
https://www.amazon.fr/Clean-Code-Handbook-Software-Craftsmanship/dp/0132350882

"il est commenté et organisé autour d'un switch"
comments are not necessary if code is clean.

http://jsonapi.org/format/#fetching
http://jsonapi.org/format/#crud
http://www.restapitutorial.com/lessons/restquicktips.html
everything is done in GET

**Comment by patoninho1** [comment]
Thanks you very much for the book, 
it will help me a lot ...
http://ricardogeek.com/docs/clean_code.pdf
i found it for free btw

**Comment by patoninho1** [comment]
I made many changes could you check my code please.
Thanks
